### ISSUE TITLE
Input files missing

### ISSUE THREAD

**Issue by JoaoLopez** [timothygmitchell/Scientific_Glassware_Deep_Learning#1]
Hi, Timothy

I forked your repository and tried to execute the file **Scientific_Glassware_Python_Code.py**, but the input files are missing. Could you add them to the repository?

Thanks in advance!

João López

**Comment by timothygmitchell** [comment]
Hello, unfortunately the files took up a lot of space and I have long since deleted them. In any event, keras is a good deep learning library for applications but if I could do it over again, I might use Pytorch. It is more pythonic.

If you want to run the code then you could find a dataset of dogs, cats, etc. or another established data set. The premise ought to be the same.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: JoaoLopez ***@***.***>
Sent: Monday, June 13, 2022 11:45:13 AM
To: timothygmitchell/Scientific_Glassware_Deep_Learning ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [timothygmitchell/Scientific_Glassware_Deep_Learning] Input files missing (Issue #1)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.


Hi, Timothy

I forked your repository and tried to execute the file Scientific_Glassware_Python_Code.py, but the input files are missing. Could you add them to the repository?

Thanks in advance!

João López

**Comment by JoaoLopez** [comment]
Oh, ok. Thank you very much for your help!
